### PR TITLE
ERD: Embed instead of img linking

### PR DESCRIPTION
**Pull request by ghost**
This makes fonts work:
https://github.com/openreferral/specification/issues/266#issuecomment-993587618

                        
We make sure svg files are placed in same place as before in built site:
* for backwards compatibility                                           
* _images feels like the right place anyway

### CODE REVIEW

**Comment by odscjames** [comment]
WIP as I'd like to double test.

But first @robredpath does http://docs.openreferral.org/en/266-svg-fonts/hsds/logical_model/#er-diagram look good? It changes in that the whole diagram isn't clickable now but there is a link below and when you hover over a table you get a popup of info.

**Comment by robredpath** [comment]
Thanks @odscjames 

When I move my mouse around the page, I see the cursor change as I move between background and table, but when I click, nothing happens. Disabling my adblocker doesn't do anything, and I don't get any browser permission prompts either.

**Comment by odscjames** [comment]
Yes, there are `<a>` tags round each table object to which titles are attached. The same doesn't happen on the big version ( http://docs.openreferral.org/en/latest/_images/entity_relationship_diagram_core_tables.svg ) which is a bit odd, but then https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:title says it's deprecated so maybe that explains it.

The a tags are not added by our library; I assume they are added by Graphviz? They can be removed by not passing the `tooltip` option to `graph.add_node` in the `_graph_add_table` definition in our library, but then the popup text becomes just the table name in lower case. Maybe that's a better popup text than the description anyway?

**Comment by robredpath** [comment]
@odscjames ah, I see! I have no particular views on the tooltip - it's just the same info as is on the tables, so it doesn't really matter that people may well not see it: it's not the kind of thing that I'd ever think to hover over for more info. 

It's a bit confusing that things look clickable but then don't do anything, especially when they're too small to read: I'd really expect that to provide some sort of zoomed-in view or a modal or something like that. 

Maybe the `<a>` tags are getting added by hypothesis? I'm not sure - one to look into.

**Comment by odscjames** [comment]
> Maybe the <a> tags are getting added by hypothesis? I'm not sure - one to look into.

No, I can remove that and it still happens. It's the tooltips.

Ok, we'll need a PR in the ERD library too to deliver this then.

**Comment by odscjames** [comment]
Preview at http://docs.openreferral.org/en/266-svg-fonts/hsds/logical_model/#er-diagram

**Comment by robredpath** [comment]
This looks good, but I'm not sure it's clear that the "View full version of diagram" links relate to the diagrams directly above them, at least not at first glance. 

Could we make the entire diagram clickable to open the image, or have some kind of "open full size" icon / link just below the relevant heading?>

**Comment by odscjames** [comment]
> Could we make the entire diagram clickable to open the image,

I tried that and there wasn't an obvious good way, but I'll double check.

> have some kind of "open full size" icon / link just below the relevant heading?

I can move the link up so it's just below the heading at least.

**Comment by odscjames** [comment]
@robredpath link moved

**Comment by robredpath** [comment]
Great - we're getting there! Last up - I'm not sure that "full version" is what we want when we already say (Full version) to refer to a version of the ERD. 

How about "[enlarge]" or make it open in a new window with the next "Open in a new window"?

**Comment by odscjames** [comment]
@robredpath Changed

**Review by robredpath — APPROVED** [review]

**Pull request merged**
