### PR TITLE
Core Tables, including an ERD diagram

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by odscjames** [comment]
See at http://docs.openreferral.org/en/core-tables-inc-er-diagram/hsds/logical_model/#er-diagram

**Comment by odscjames** [comment]
http://docs.openreferral.org/en/core-tables-inc-er-diagram/hsds/logical_model/#er-diagram - note it's maybe a bit odd because the service table has "program_id" which IS a foreign key but it's not shown as such in the diagram anywhere.

**Review by robredpath — APPROVED** [review]

**Comment by robredpath** [comment]
Thanks, @odscjames - I'm happy that it's working given that link, and I'm happy with the implementation. That makes sense about the program, but I think it's OK; this is a diagram for helping people to grok the very basics of the standard.

**Comment by robredpath** [comment]
@odscjames We should probably roll up these changes into a MINOR release (all these docs are part of the standard!) , but pragmatically I'm pretty happy for us to crack on with getting things merged and then do a release at the end.

**Pull request merged**
