### PR TITLE
mysql: Fix build

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by odscjames** [comment]
WIP because this is ok but I'd like to see if this is a temporary glitch

**Comment by odscjames** [comment]
Ok, this sorts out the database issue but it's a bit hacky. I'll leave this here if anyone needs it, but maybe this problem will sort itself out.

**Comment by odscjames** [comment]
Still seems to be an issue, putting in

**Review by robredpath — APPROVED** [review]

**Comment by robredpath** [comment]
That's weird, but I'll approve and we can revisit it later if it causes issues anywhere @odscjames

**Pull request merged**
